---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: openaichat-ui
spec:
  serviceAccountName: pipeline
  triggers:
  - bindings:
    - ref: openaichat-ui
    template:
      ref: openaichat-ui