apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- ../../base

namespace: aro-azureopenai
images:
- digest: sha256:1c3ac1c9d5fb7a50e9f0512b9de036b286f2ebfaabdc14741dd65f34379079af
  name: quay.io/sombaner-mobb-apac/aro-azureopenai:latest
  newName: quay.io/sombaner-mobb-apac/aro-azureopenai
  newTag: latest
