apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- ../../base

namespace: aro-azureopenai
images:
- digest: sha256:779018224767608e04897334c00deeef38bd0b24fbc239521d0ba6486fd200c1
  name: quay.io/sombaner-mobb-apac/aro-azureopenai:latest
  newName: quay.io/sombaner-mobb-apac/aro-azureopenai
  newTag: latest
