apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- ../../base

namespace: aro-azureopenai
images:
- digest: sha256:33efadc292de68e0516911a38dd6b3905362e7cf60967992654f1013cfca0114
  name: quay.io/sombaner-mobb-apac/aro-azureopenai:latest
  newName: quay.io/sombaner-mobb-apac/aro-azureopenai
  newTag: latest
