apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- ../../base

namespace: aro-azureopenai
images:
- digest: sha256:b82f052dbe6f753b8958bcf159e0257d7fafd367e1ef2d8c6b5233a402092e27
  name: quay.io/sombaner-mobb-apac/aro-azureopenai:latest
  newName: quay.io/sombaner-mobb-apac/aro-azureopenai
  newTag: latest
