apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- route.yaml
- ../../base

namespace: aro-azureopenai
images:
- digest: sha256:3a4bed273b78891dd05e5ed6b70f15abb5f4bf19574b37ccc8675e4186f99b1f
  name: quay.io/sombaner-mobb-apac/aro-azureopenai:latest
  newName: quay.io/sombaner-mobb-apac/aro-azureopenai
  newTag: latest
